### PR TITLE
Accepted answer and remove accepted answer functionality

### PR DESCRIPTION
**Pull request by markKovacs**
Implement mark accepted answer and remove accepted answer, show accepted answer on question.html implemented html/css wise. In the process, show_question_page in main now receives all the updated info from database (based on updated schema) and displays everything properly on question.html.

### CODE REVIEW

**Review by matebalogh11 — APPROVED** [review]
I like it!:)

**Review by alextakacs10 — APPROVED** [review]
GG.WP.

**Review by annabellaMalatinszki — APPROVED** [review]
oh so beautiful my dear

**Comment by markKovacs** [comment]
Thank you for your effort. I am merging accepted_answer branch into develop. Feel free to pull afterwards.

**Pull request closed without merging**
